# Generated by Django 5.2.3 on 2025-09-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(db_index=True)),
                ('shop_id', models.IntegerField(db_index=True)),
                ('stock', models.IntegerField(default=0)),
                ('reserved', models.IntegerField(default=0)),
                ('threshold', models.IntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('product_id', 'shop_id')},
            },
        ),
    ]
